#!/bin/sh
# Run Prettier on staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx|css|json|md)$')
if [ -n "$STAGED_FILES" ]; then
  npx prettier --write $STAGED_FILES
  git add $STAGED_FILES
fi
